defaults:
  - env/libero_spatial@env.train
  - env/libero_spatial@env.eval
  - model/pi0_5@actor.model
  - training_backend/fsdp@actor.fsdp_config
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

cluster:
  num_nodes: 1
  component_placement:
    actor,env,rollout: 0-0

runner:
  task_type: embodied
  logger:
    log_path: "../results"
    project_name: rlinf
    experiment_name: "libero_spatial_grpo_openpi_pi05"
    logger_backends: ["tensorboard"] # wandb, swanlab

  max_epochs: 1000
  max_steps: -1

  only_eval: False
  val_check_interval: -1
  save_interval: 40

  resume_dir: null # Optional: path to a saved checkpoint directory, such as 'checkpoints/global_step_10'. If not None, it will be used to resume training.
  ckpt_path: null  # Optional: path to a .pt checkpoint. If not None, it will be loaded after the model is instantiated (for evaluation).

algorithm:
  normalize_advantages: True
  kl_penalty: kl  # how to estimate kl divergence: kl or kl_penalty
  group_size: 8
  reward_coef: 1.0
  rollout_epoch: 8
  eval_rollout_epoch: 50 # set eval_rollout_epoch > 0 when enable runner.only_eval or runner.val_check_interval > 0

  reward_type: chunk_level
  logprob_type: chunk_level
  entropy_type: token_level
  update_epoch: 1

  adv_type: grpo
  loss_type: actor
  loss_agg_func: "token-mean" 
  kl_beta: 0.0
  entropy_bonus: 0
  clip_ratio_high: 0.2
  clip_ratio_low: 0.2
  clip_ratio_c: 3.0
  value_clip: 0.2
  huber_delta: 10.0

  gamma: 0.99
  gae_lambda: 0.95

  filter_rewards: True
  rewards_lower_bound: 0.1
  rewards_upper_bound: 0.9
  # params for generation
  sampling_params:
    do_sample: True
    temperature_train: 1.0
    temperature_eval: 0.6
    top_k: 50
    top_p: 1.0
    repetition_penalty: 1.0
    add_BOS: False

  # length argument for autoregressive sampling
  # max length means max amount of tokens to generate
  length_params:
    max_new_token: null
    max_length: 1024
    min_length: 1

env:
  group_name: "EnvGroup"
  enable_offload: False

  # Override the default values in env/libero_spatial
  train:
    total_num_envs: 64
    group_size: ${algorithm.group_size}
    max_episode_steps: 240 # max episode steps for truncation
    max_steps_per_rollout_epoch: 240
  eval:
    total_num_envs: 10
    auto_reset: True
    ignore_terminations: True
    max_episode_steps: 240
    max_steps_per_rollout_epoch: 240
    group_size: 1
    is_eval: True
    video_cfg:
      save_video: True
      video_base_dir: ${runner.logger.log_path}/video/eval

rollout:
  group_name: "RolloutGroup"
  generation_backend: "huggingface"
  recompute_logprobs: False
  unnorm_key: libero_10
  enable_offload: False
  pipeline_stage_num: 1

  model:
    model_path: "/home/feng/data/wxh/SpecRlinf/models/pi05_pytorch"
    precision: ${actor.model.precision}

actor:
  group_name: "ActorGroup"
  training_backend: "fsdp"
  micro_batch_size: 128
  global_batch_size: 2048 # maximum : global batch size = micro batch size * actor num_processes.
  seed: 42
  enable_offload: False

  # Override the default values in model/pi0_5
  model:
    model_path: "/home/feng/data/wxh/SpecRlinf/models/pi05_pytorch"
    num_action_chunks: 10 # interface for the env
    num_steps: 3
    openpi:
      action_horizon: 10
      eval_action_horizon:  10  # only execute first 6 steps in eval when spec is off
      enable_speculative: False
      spec_batch_size: 8
      spec_action_horizon: 10
      spec_diffusion_num_steps: 3
      spec_chunk_size: 5
      rollout_segment: False
      rollout_segment_size: 5
      spec_conf_alpha: 0.8
      spec_conf_eps: 1.0e-8
      spec_delta_thresholds: [0.2,0.2,0.3,0.1,0.1,0.1]
      # spec_delta_thresholds: [.5,.5, 3.0]
      spec_debug: True
      spec_profile_timing: False

  optim:
    lr: 5.0e-6
    value_lr: 1.0e-4
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-05
    weight_decay: 0.01
    clip_grad: 1.0

  # Override the default values in training_backend/fsdp
  fsdp_config:
    strategy: "fsdp"
    sharding_strategy: "no_shard"
    gradient_checkpointing: False # for openpi, gradient checkpointing is not supported, please do not change this value
    mixed_precision:
      param_dtype: ${actor.model.precision}
      reduce_dtype: ${actor.model.precision}
      buffer_dtype: ${actor.model.precision}

reward:
  use_reward_model: False

critic:
  use_critic_model: False